### ISSUE TITLE
Go back in time

### ISSUE THREAD

**Issue by betegon** [pkaske/tv-shooter#3]
Hi @pkaske 

Thank you for your hard work!

As far as I know, it is not possible to go back in time in the chart.

**Do you think this is achievable?** I am interested on it I will like a bit of guidance if possible.

Looking to hear from you,

Kind regards.

**Comment by pkaske** [comment]
Hi,

you would need to figure out how to programmatically start and control the replay feature.
It's probable that there are APIs in the TradingView site to do that.

If that works it would just be a matter of extending request params.

**Comment by betegon** [comment]
Hi @pkaske 
Thank you for you answer. I don't even need to use replay feature, just go back in time to specific date and set the price axis (y axis) to a specific value.

Have you been able to get axis values using selenium? It is kind of new to me.

Thanks again!

**Comment by pkaske** [comment]
Ah you mean moving the time axis. Yeah you would need to automate that goto feature that let's you set a date and a time I guess. The project isn't using selenium. It's using puppeteer tho.

**Comment by betegon** [comment]
Thank you so much, and sorry for bothering you.

I don't know why I think it was using selenium!
